image: Visual Studio 2017

skip_branch_with_pr: true
  
before_build:
  - nuget restore Vk.Api.Schema.sln
    
dotnet_csproj:
  patch: true
  file: src\Vk.Api.Schema\Vk.Api.Schema.csproj
  version: $(appveyor_build_version)
  package_version: $(appveyor_build_version)
  
build:
    project: Vk.Api.Schema.sln
    publish_nuget: true
    publish_nuget_symbols: false
    verbosity: minimal

deploy:
 - provider: NuGet
   api_key:
     secure: swbVO/mLDF9LqZnkMZJ2YDtPkdPyjQxrqLk79gYbBaT/fbhkmEGPEpuYZqyor9RK
   artifact: /.*\.nupkg/
   on:
     branch: some_branch
     
 - provider: NuGet
   server: https://www.myget.org/F/vk-api-schema/api/v2/package
   api_key:
     secure: 5hNHtZsz8pxougmcZNm9qlwWzQn0MT6CP5PX8CXcBki9Ve1hB8h1l4PEPsuA8QFK
   artifact: /.*\.nupkg/
   on:
     branch: master
